# Doctrine Configuration
doctrine:
    dbal:
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
               mappings:
                   AppBundle: ~
                   DomainModel:
                       type: xml
                       dir: '%kernel.root_dir%/Resources/infrastructure/persistence/doctrine'
                       is_bundle: false
                       prefix: Domain\Model
                       alias: DomainModel
            test:
                mappings:
                   AppBundle: ~
                   DomainModel:
                       type: xml
                       dir: '%kernel.root_dir%/Resources/infrastructure/persistence/doctrine'
                       is_bundle: false
                       prefix: Domain\Model
                       alias: DomainModel