<?php
/**
 * Shiporder
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shiporders
 *
 * This is a sample server Shiporders server. For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: junio.webmaster@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Shiporder model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class Shiporder 
{
        /**
     * @var int|null
     * @SerializedName("orderid")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $orderid;

    /**
     * @var int|null
     * @SerializedName("orderperson")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $orderperson;

    /**
     * @var Swagger\Server\Model\Shipto|null
     * @SerializedName("shipto")
     * @Assert\Type("Swagger\Server\Model\Shipto")
     * @Type("Swagger\Server\Model\Shipto")
     */
    protected $shipto;

    /**
     * @var Swagger\Server\Model\Item[]|null
     * @SerializedName("items")
     * @Assert\All({
     *   @Assert\Type("Swagger\Server\Model\Item")
     * })
     * @Type("array<Swagger\Server\Model\Item>")
     */
    protected $items;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->orderid = isset($data['orderid']) ? $data['orderid'] : null;
        $this->orderperson = isset($data['orderperson']) ? $data['orderperson'] : null;
        $this->shipto = isset($data['shipto']) ? $data['shipto'] : null;
        $this->items = isset($data['items']) ? $data['items'] : null;
    }

    /**
     * Gets orderid.
     *
     * @return int|null
     */
    public function getOrderid()
    {
        return $this->orderid;
    }

    /**
     * Sets orderid.
     *
     * @param int|null $orderid
     *
     * @return $this
     */
    public function setOrderid($orderid = null)
    {
        $this->orderid = $orderid;

        return $this;
    }

    /**
     * Gets orderperson.
     *
     * @return int|null
     */
    public function getOrderperson()
    {
        return $this->orderperson;
    }

    /**
     * Sets orderperson.
     *
     * @param int|null $orderperson
     *
     * @return $this
     */
    public function setOrderperson($orderperson = null)
    {
        $this->orderperson = $orderperson;

        return $this;
    }

    /**
     * Gets shipto.
     *
     * @return Swagger\Server\Model\Shipto|null
     */
    public function getShipto()
    {
        return $this->shipto;
    }

    /**
     * Sets shipto.
     *
     * @param Swagger\Server\Model\Shipto|null $shipto
     *
     * @return $this
     */
    public function setShipto(Shipto $shipto = null)
    {
        $this->shipto = $shipto;

        return $this;
    }

    /**
     * Gets items.
     *
     * @return Swagger\Server\Model\Item[]|null
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Sets items.
     *
     * @param Swagger\Server\Model\Item[]|null $items
     *
     * @return $this
     */
    public function setItems(Item $items = null)
    {
        $this->items = $items;

        return $this;
    }
}


